<?php

namespace Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends EntityRepository
{
    public function findAllPedidos(){
        $query = $this->getEntityManager()
        ->createQuery('
            SELECT p.id_pedido
              FROM Entity\Empresa e,
                   Entity\Cp\Pedido p
             WHERE e.id_empresa = p.id_empresa 
               AND p.id_pedido = :id_pedido'
        )->setParameter('id_pedido', 272317);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}